### ISSUE TITLE
Do not found subtitles (scenario)

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/sub-tv#1]
Case to test:
- *Série*: Grey's anatomy
- *Season*: 1
- *Episodes*:  

In this scenario, it shows any episode and it is not possible to return to previous question.

It **must** to inform that do not have any subtitles for this season and return to *Season question*.

**Comment by machad0** [comment]
hey, do you mind if I take that issue? really nice project, tho

**Comment by raulfdm** [comment]
@machad0 Of course not =D Go ahead... I'm thinking to start a big refactoring using TDD

**Comment by machad0** [comment]
Ok! I'll be working on it later.
Looking forward to updates. Fell free to assign me to backlog issues, features, etc.

cheers

**Comment by raulfdm** [comment]
@machad0 2 years and a half.

I've switch the provider and now this kind of error won't happen anymore! 😄
