### ISSUE TITLE
Add more providers

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/sub-tv#2]
Find more subtitles websites to add as a provider.

**Comment by machad0** [comment]
We shoudl add [open-subtitles](https://www.opensubtitles.org) to the providers using [opensubtitles-api](https://www.npmjs.com/package/opensubtitles-api). Also, would be cool if we had a service to fetch all the sources, instead binding it to the Series service at `service/Series.js`.

What do you say about it? Btw, didn't had time yet to code the other issues. I'll be working on it ASAP. :)

**Comment by raulfdm** [comment]
@machad0 I was thinking to use this service. I've made some tests but without auth. It could be a good idea. Open-subtitles is a very good provider.

Do you know Typescript? I'm refactoring to use it and improve code/test quality!

**Comment by machad0** [comment]
Yep, also would be cool to detect the source kind, i.e, if is a movie or a tv serie.
 
And I never worked with typescript before, just made a few sandboxes. Learn by following the project's style guide seems like an awesome way to learn it!

**Comment by raulfdm** [comment]
@machad0 cool.. I've started to refactoring using Typescript and trying to use TDD as methodology. #4 

I've found a lib to test inquirerjs and I'll implement all this tests!
