### ISSUE TITLE
Do not found any subtitles

### ISSUE THREAD

**Issue by robertopc** [raulfdm/sub-tv#7]
I installed and in usage not found any subtitle.

My software specifications are follow:
OS: Lubuntu 16.04.1
NodeJS: v9.3.0
NPM: 5.5.1

I recorded a asciinema to demonstrate.

[![asciicast](https://asciinema.org/a/oBv04Ah1hhzZnkZbQtNReyIX4.png)](https://asciinema.org/a/oBv04Ah1hhzZnkZbQtNReyIX4)

**Comment by raulfdm** [comment]
Hi @robertopc . I'll check it out! Thanks for the feedback! :)

**Comment by raulfdm** [comment]
I've just checked, the guys changed something in API. Will work on it!

**Comment by raulfdm** [comment]
- b35222d70e494f87ae884830007ae5c46d4cbfa4
- ef1f576f03ccd0b8fe5c22c3457c717af3775300
- e434e2ea36920b945c2dd5d5fd441093de4e764d
- de4f4f40f7953914726a50ea8bb746b139c74142

**Comment by raulfdm** [comment]
@robertopc fixed! Could you try to upgrade? The latest version is `0.0.5`! Cheers!

**Comment by robertopc** [comment]
Ok. I will test.
